version: "3"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  matomo:
    image: matomo
    links:
      - db

  portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - matomo
    environment:
      DOMAINS: "analytics.minsky.cc -> http://matomo:80"
      STAGE: "production"
